name: CI - Build, Test, and Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Run Tests
        run: mvn -B clean test

      - name: Generate Allure Report
        run: |
          REPORT_NAME="Allure-Report-$(date +'%Y-%m-%d_%H-%M-%S')"
          mvn allure:report -Dallure.report.directory=target/$REPORT_NAME
      

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/$REPORT_NAME

  deploy-report:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Reports
        uses: actions/download-artifact@v4
        with:
          name: cucumber-reports
          path: target/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Allure Site
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site/allure-maven-plugin

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
